# Generated by Django 3.2.12 on 2022-09-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntntsno', models.CharField(blank=True, db_column='cntntsNo', max_length=255, null=True)),
                ('cntntssj', models.CharField(blank=True, db_column='cntntsSj', max_length=255, null=True)),
                ('adviseinfo', models.CharField(blank=True, db_column='adviseInfo', max_length=255, null=True)),
                ('clcodenm', models.CharField(blank=True, db_column='clCodeNm', max_length=255, null=True)),
                ('dlthtscodenm', models.CharField(blank=True, db_column='dlthtsCodeNm', max_length=255, null=True)),
                ('dlthtsmanageinfo', models.CharField(blank=True, db_column='dlthtsManageInfo', max_length=255, null=True)),
                ('eclgycodenm', models.CharField(blank=True, db_column='eclgyCodeNm', max_length=255, null=True)),
                ('etcerainfo', models.CharField(blank=True, db_column='etcEraInfo', max_length=255, null=True)),
                ('flclrcodenm', models.CharField(blank=True, db_column='flclrCodeNm', max_length=255, null=True)),
                ('fmlcodenm', models.CharField(blank=True, db_column='fmlCodeNm', max_length=255, null=True)),
                ('fmldeseasoncodenm', models.CharField(blank=True, db_column='fmldeSeasonCodeNm', max_length=255, null=True)),
                ('fmldecolrcodenm', models.CharField(blank=True, db_column='fmldecolrCodeNm', max_length=255, null=True)),
                ('fncltyinfo', models.CharField(blank=True, db_column='fncltyInfo', max_length=2000, null=True)),
                ('frtlzrinfo', models.CharField(blank=True, db_column='frtlzrInfo', max_length=255, null=True)),
                ('growtharainfo', models.CharField(blank=True, db_column='growthAraInfo', max_length=255, null=True)),
                ('growthhginfo', models.CharField(blank=True, db_column='growthHgInfo', max_length=255, null=True)),
                ('grwhtpcodenm', models.CharField(blank=True, db_column='grwhTpCodeNm', max_length=255, null=True)),
                ('grwhstlecodenm', models.CharField(blank=True, db_column='grwhstleCodeNm', max_length=255, null=True)),
                ('grwtvecodenm', models.CharField(blank=True, db_column='grwtveCodeNm', max_length=255, null=True)),
                ('hdcodenm', models.CharField(blank=True, db_column='hdCodeNm', max_length=255, null=True)),
                ('ignseasoncodenm', models.CharField(blank=True, db_column='ignSeasonCodeNm', max_length=255, null=True)),
                ('lefstleinfo', models.CharField(blank=True, db_column='lefStleInfo', max_length=255, null=True)),
                ('lefcolrcodenm', models.CharField(blank=True, db_column='lefcolrCodeNm', max_length=255, null=True)),
                ('lefmrkcodenm', models.CharField(blank=True, db_column='lefmrkCodeNm', max_length=255, null=True)),
                ('lighttdemanddocodenm', models.CharField(blank=True, db_column='lighttdemanddoCodeNm', max_length=255, null=True)),
                ('managedemanddocodenm', models.CharField(blank=True, db_column='managedemanddoCodeNm', max_length=255, null=True)),
                ('managelevelcodenm', models.CharField(blank=True, db_column='managelevelCodeNm', max_length=255, null=True)),
                ('orgplceinfo', models.CharField(blank=True, db_column='orgplceInfo', max_length=255, null=True)),
                ('postngplacecodenm', models.CharField(blank=True, db_column='postngplaceCodeNm', max_length=255, null=True)),
                ('prpgterainfo', models.CharField(blank=True, db_column='prpgtEraInfo', max_length=255, null=True)),
                ('prpgtmthcodenm', models.CharField(blank=True, db_column='prpgtmthCodeNm', max_length=255, null=True)),
                ('smellcodenm', models.CharField(blank=True, db_column='smellCodeNm', max_length=255, null=True)),
                ('soilinfo', models.CharField(blank=True, db_column='soilInfo', max_length=255, null=True)),
                ('speclmanageinfo', models.CharField(blank=True, db_column='speclmanageInfo', max_length=2000, null=True)),
                ('toxctyinfo', models.CharField(blank=True, db_column='toxctyInfo', max_length=255, null=True)),
                ('watercycleautumncodenm', models.CharField(blank=True, db_column='watercycleAutumnCodeNm', max_length=255, null=True)),
                ('watercyclesprngcodenm', models.CharField(blank=True, db_column='watercycleSprngCodeNm', max_length=255, null=True)),
                ('watercyclesummercodenm', models.CharField(blank=True, db_column='watercycleSummerCodeNm', max_length=255, null=True)),
                ('watercyclewintercodenm', models.CharField(blank=True, db_column='watercycleWinterCodeNm', max_length=255, null=True)),
                ('winterlwettpcodenm', models.CharField(blank=True, db_column='winterLwetTpCodeNm', max_length=255, null=True)),
            ],
            options={
                'db_table': 'plant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plantrecomm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cntntsno', models.CharField(blank=True, db_column='cntntsNo', max_length=255, null=True)),
                ('cntntssj', models.CharField(blank=True, db_column='cntntsSj', max_length=255, null=True)),
                ('presentadequacy', models.IntegerField(blank=True, db_column='presentAdequacy', null=True)),
                ('aircleaning', models.CharField(blank=True, db_column='airCleaning', max_length=3, null=True)),
                ('particulatematter', models.CharField(blank=True, db_column='particulateMatter', max_length=3, null=True)),
                ('petsafety', models.IntegerField(blank=True, db_column='petSafety', null=True)),
                ('scent', models.IntegerField(blank=True, null=True)),
                ('humidify', models.IntegerField(blank=True, null=True)),
                ('allergy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plantRecomm',
                'managed': False,
            },
        ),
    ]
