# Generated by Django 3.2.12 on 2022-09-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_no', models.CharField(blank=True, db_column='cntntsNo', max_length=255, null=True, verbose_name='식물 번호')),
                ('plant_name', models.CharField(blank=True, db_column='cntntsSj', max_length=255, null=True, verbose_name='식물 이름')),
                ('present_adequacy', models.IntegerField(blank=True, db_column='presentAdequacy', null=True, verbose_name='선물 적합성')),
                ('air_cleaning', models.CharField(blank=True, db_column='airCleaning', max_length=3, null=True, verbose_name='공기 정화 기능')),
                ('pm_cleaning', models.CharField(blank=True, db_column='particulateMatter', max_length=3, null=True, verbose_name='미세먼지 정화 기능')),
                ('pet_safety', models.IntegerField(blank=True, db_column='petSafety', null=True, verbose_name='반려동물 안전성')),
                ('humidify', models.IntegerField(blank=True, db_column='humidify', null=True, verbose_name='가습 효과')),
                ('toxicity', models.IntegerField(blank=True, db_column='toxcty', null=True, verbose_name='독성')),
            ],
            options={
                'db_table': 'plantRecomm',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Plantrecomm',
        ),
    ]
