# Generated by Django 3.2.12 on 2022-09-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20220922_1624'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='plantkeyword',
            table='plantKeyword',
        ),
    ]
