# Generated by Django 3.2.12 on 2022-10-01 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_content_user_description'),
        ('plants', '0003_alter_plantkeyword_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantlike',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.user')),
                ('score', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'plantlike',
                'managed': False,
            },
        ),
    ]
