# Generated by Django 3.2.12 on 2022-10-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plantlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'update_table',
                'managed': False,
            },
        ),
    ]
