# Generated by Django 3.2.12 on 2022-10-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_updatetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantlike',
            name='user',
        ),
        migrations.DeleteModel(
            name='UpdateTable',
        ),
        migrations.DeleteModel(
            name='Plantlike',
        ),
    ]
