# Generated by Django 3.2.12 on 2022-09-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.IntegerField(default=0, verbose_name='경험치'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=10, verbose_name='닉네임'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=0, verbose_name='포인트'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.TextField(null=True, verbose_name='프로필 사진'),
        ),
    ]
