# Generated by Django 3.2.12 on 2022-09-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age_group',
            field=models.CharField(max_length=10, null=True, verbose_name='연령대'),
        ),
    ]
