# Generated by Django 3.2.12 on 2022-09-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='content',
            field=models.TextField(default='한줄 소개가 없습니다.', verbose_name='한줄 소개'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='나의 정원 비공개 설정'),
        ),
    ]
