# Generated by Django 3.2.12 on 2022-09-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220926_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='content',
            new_name='description',
        ),
    ]
