# Generated by Django 3.2.12 on 2022-09-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygardens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='plant',
        ),
    ]
