# Generated by Django 3.2.12 on 2022-09-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygardens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='date_grow',
            field=models.DateField(null=True, verbose_name='키운날짜'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='img_url',
            field=models.TextField(null=True, verbose_name='식물 사진'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='recent_water',
            field=models.DateField(null=True, verbose_name='최근 물 준 날짜'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='watering_schedule',
            field=models.IntegerField(null=True, verbose_name='물주기 주기'),
        ),
    ]
