# Generated by Django 3.2.12 on 2022-09-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygardens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mygarden',
            name='plant',
        ),
    ]
