# Generated by Django 3.2.12 on 2022-09-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        ('mygardens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plants.plant', verbose_name='플랜트 이름'),
            preserve_default=False,
        ),
    ]
