# Generated by Django 3.2.12 on 2022-09-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygardens', '0002_auto_20220921_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='memo',
            field=models.TextField(null=True, verbose_name='한줄소개 메모'),
        ),
    ]
