# Generated by Django 3.2.12 on 2022-09-27 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20220922_1624'),
        ('mygardens', '0002_remove_mygarden_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygarden',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plants.plant', verbose_name='플랜트 PK'),
            preserve_default=False,
        ),
    ]
