# Generated by Django 3.2.12 on 2022-09-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygardens', '0003_mygarden_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygarden',
            name='present',
            field=models.BooleanField(default=False, verbose_name='선물용 여부'),
        ),
    ]
