# Generated by Django 3.2.12 on 2022-09-21 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mygardens', '0003_garden_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('date_grow', models.DateField(null=True, verbose_name='키운 날짜')),
                ('watering_schedule', models.IntegerField(null=True, verbose_name='물주는 주기')),
                ('recent_water', models.DateField(null=True, verbose_name='최근 물 준 날짜')),
                ('diaries_count', models.IntegerField(default=0, verbose_name='일기 개수')),
                ('img_url', models.TextField(null=True, verbose_name='식물 사진')),
                ('memo', models.TextField(null=True, verbose_name='한줄소개 메모')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant', verbose_name='플랜트 이름')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.RemoveField(
            model_name='diary',
            name='garden',
        ),
        migrations.AlterField(
            model_name='diary',
            name='diary_img',
            field=models.TextField(null=True, verbose_name='식물일기 사진'),
        ),
        migrations.DeleteModel(
            name='Garden',
        ),
        migrations.AddField(
            model_name='diary',
            name='my_garden',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='mygardens.mygarden', verbose_name='나의 정원 PK'),
            preserve_default=False,
        ),
    ]
