# Generated by Django 3.2.12 on 2022-10-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygardens', '0005_mygarden_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygarden',
            name='keep',
            field=models.BooleanField(default=False, verbose_name='식물 보관 여부'),
        ),
    ]
