# Generated by Django 3.2.12 on 2022-09-21 02:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='읽을거리 작성일자')),
                ('img_url', models.TextField(verbose_name='사진')),
                ('comments_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='댓글 개수')),
                ('likes_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='좋아요 개수')),
            ],
        ),
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='좋아요 누른 시각')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.feed', verbose_name='남의 정원 PK')),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='내 아이디')),
            ],
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='댓글 작성일')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.feed', verbose_name='남의 정원 PK')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='내 아이디')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='likes',
            field=models.ManyToManyField(related_name='like_feeds', through='feeds.FeedLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
