# Generated by Django 3.2.12 on 2022-10-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_remove_user_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantlike',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.user')),
                ('score', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'plantlike',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'update_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserKeywordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_safe', models.IntegerField(blank=True, null=True, verbose_name='반려동물 안전성')),
                ('humidify', models.IntegerField(blank=True, null=True, verbose_name='가습 기능')),
                ('pm_cleaning', models.IntegerField(blank=True, null=True, verbose_name='미세먼지 정화 기능')),
                ('beginner', models.IntegerField(blank=True, null=True, verbose_name='초보자용')),
                ('unscented', models.IntegerField(blank=True, null=True, verbose_name='무향')),
                ('hydroponics', models.IntegerField(blank=True, null=True, verbose_name='수경 재배 가능')),
                ('low_growth_demand', models.IntegerField(blank=True, null=True, verbose_name='손쉬운 관리')),
                ('low_light_demand', models.IntegerField(blank=True, null=True, verbose_name='적은 빛')),
                ('low_temp', models.IntegerField(blank=True, null=True, verbose_name='낮은 온도')),
                ('air_cleaning', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recommendations_userkeywordcount',
                'managed': False,
            },
        ),
    ]
