# Generated by Django 3.2.12 on 2022-09-28 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeywordCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_safe', models.IntegerField(default=0, verbose_name='반려동물 안전성')),
                ('humidify', models.IntegerField(default=0, verbose_name='가습 기능')),
                ('pm_cleaning', models.IntegerField(default=0, verbose_name='미세먼지 정화 기능')),
                ('beginner', models.IntegerField(default=0, verbose_name='초보자용')),
                ('unscented', models.IntegerField(default=0, verbose_name='무향')),
                ('hydroponics', models.IntegerField(default=0, verbose_name='수경 재배용')),
                ('low_growth_demand', models.IntegerField(default=0, verbose_name='손쉬운 관리')),
                ('low_light_demand', models.IntegerField(default=0, verbose_name='적은 빛')),
                ('low_temp', models.IntegerField(default=0, verbose_name='낮은 온도')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
    ]
