# Generated by Django 3.2.12 on 2022-10-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkeywordcount',
            options={},
        ),
    ]
