# Generated by Django 3.2.12 on 2022-10-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_alter_userkeywordcount_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkeywordcount',
            options={'managed': False},
        ),
    ]
