# Generated by Django 3.2.12 on 2022-09-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_content_user_description'),
        ('recommendations', '0002_userkeywordcount_air_cleaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantlike',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('score', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'plantLike',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateTable',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'update_table',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='userkeywordcount',
            name='air_cleaning',
        ),
    ]
