# Generated by Django 3.2.12 on 2022-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_auto_20220929_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkeywordcount',
            name='air_cleaning',
            field=models.IntegerField(default=0, verbose_name='공기 정화 기능'),
        ),
    ]
