# Generated by Django 3.2.12 on 2022-10-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_plantlike_updatetable'),
        ('recommendations', '0004_userkeywordcount_air_cleaning'),
    ]

    operations = [
    ]
